/**
 * DO NOT EDIT THIS FILE!
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE SYSTEM!
 * GENERATED AT 2018-09-07 15:30:13
 **/

/**
 * 프로모션 배너
 **/
var bottom_promotions = new Array(
    { 'link_url': 'http://conference.etnews.com/conf_info.html?uid=95', 'banner_url': 'http://img.etnews.com/news/board/2018/09/04/board_04093839643682.jpg', 'title': '금융분야 마이데이터 활용 사례 및 비즈니스 적용방안', 'new_target': '_blank' }
);
//console.log(bottom_promotions);
//if ($('#BpromotionBanner').length && bottom_promotions.length) {
if (bottom_promotions.length) {
	$(document).ready(function() {
		// array shuffle
		bottom_promotions.sort(function() { return Math.random() * 2 - 1; });

		var str_html = '';
		var this_style = '';
		$.each(bottom_promotions, function(key, val) {
			if (key == 0) this_style = ' style="display:inline;"';
			else this_style = ' style="display:none;"';

			var new_target = '';
			if(val.new_target == 'Y' || val.new_target == '_blank') new_target = ' target="_blank"';

			str_html += '<a href="' + val.link_url + '" class="BpromotionBanner_banner"' + this_style + new_target + '><img src="' + val.banner_url + '" alt="' + val.title + '" /></a>';
		});

		//str_html += '<div class="paging1">'
		//	+ '<button class="prev1" onclick="moveTopPromotion(\'prev\'); return false;"><span class="hidden">이전</span></button><button class="next1" onclick="moveTopPromotion(\'next\'); return false;"><span class="hidden">다음</span></button>'
		//	+ '</div>';

		$('#BpromotionBanner').html(str_html);
		
		//구동
		/*
		count_top_promotion = $('.BpromotionBanner_banner').length;
		//console.log(count_top_promotion);
		if (top_promotion_timer_id) clearTimeout(top_promotion_timer_id);
		if (count_top_promotion > 1){
			//console.log(count_top_promotion);
			top_promotion_timer_id = setTimeout(function() { moveTopPromotion('next'); }, interval_promotion * 1000); // 5 seconds
		}
		*/
	});
}