/**
 * DO NOT EDIT THIS FILE!
 * THIS FILE IS AUTOMATICALLY GENERATED BY THE SYSTEM!
 * GENERATED AT 2016-08-01 09:30:21
 **/

/**
 * 프로모션 배너
 **/
/*
var top_promotions = new Array(
    { 'link_url': 'http://www.sek.co.kr/2016/patent', 'banner_url': 'http://img.etnews.com/news/board/2016/07/21/board_21160041270705.gif', 'title': '특허전쟁2', 'new_target': '' }
    , { 'link_url': 'http://www.sek.co.kr/2016/patent', 'banner_url': 'http://img.etnews.com/news/board/2016/07/21/board_21160012453416.gif', 'title': '특허전쟁1', 'new_target': '' }
    , { 'link_url': 'http://contest.etnews.com/8th/', 'banner_url': 'http://img.etnews.com/news/board/2016/06/29/board_29091147584129.jpg', 'title': 'PPT 공모 대제전', 'new_target': '' }
    , { 'link_url': 'http://www.nextdaily.co.kr/event/ideashowcase.html', 'banner_url': 'http://img.etnews.com/news/board/2015/04/10/board_10175004593605.jpg', 'title': '버즈 아이디어쇼케이스', 'new_target': 'Y' }
);

if ($('#promotionBanner').length && top_promotions.length) {
    // array shuffle
    top_promotions.sort(function() { return Math.random() * 2 - 1; });

    var str_html = '';
    var this_style = '';
    $.each(top_promotions, function(key, val) {
        if (key == 0) this_style = ' style="display:inline;"';
        else this_style = ' style="display:none;"';

        var new_target = '';
        if(val.new_target == 'Y') new_target = ' target="_blank"';

        str_html += '<a href="' + val.link_url + '" class="banner"' + this_style + new_target + '><img width="220" height="91" src="' + val.banner_url + '" alt="' + val.title + '" /></a>';
    });


    str_html += '<div class="paging1">'
        + '<button class="prev1" onclick="moveTopPromotion(\'prev\'); return false;"><span class="hidden">이전</span></button><button class="next1" onclick="moveTopPromotion(\'next\'); return false;"><span class="hidden">다음</span></button>'
        + '</div>';

    $('#promotionBanner').html(str_html);
}
*/

/**
 * 인기 검색어
 **/
var hot_queries = new Array(
    "사물인터넷"
    , "투데이 이슈"
    , "애플워치"
);

if ($('#formSearchQuery').length && hot_queries.length) {
    // array shuffle
    hot_queries.sort(function() { return Math.random() * 2 - 1; });
    $('#formSearchQuery').attr('value', hot_queries[0]);

    // 입력창이 포커스되었는 지 확인하는 플래그
    // 검색창이 처음 포커스될 때만 기존 내용 삭제
    var query_focus = false;
    $('#formSearchQuery').focus(function() {
        if (query_focus || $('#formSearchQuery').attr('value').length == 0) return;
        query_focus = true;
        $('#formSearchQuery').attr('value', '');
    });
}
